use_frameworks!

target 'SafeNSObject_Example' do
  pod 'SafeNSObject', :path => '../'

  target 'SafeNSObject_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
